# Generated by Django 4.0.1 on 2022-01-25 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
